# Generated by Django 4.2.7 on 2023-11-29 10:49

import Project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_boss',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='rasmlar', validators=[Project.models.validate_image]),
        ),
    ]
